title: <p align="center"> Teenu Francis </p>
logo: /assets/img/logo.png
description: 
<p align="center">
<br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Currently working with Maveric.
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
